server:
  port: 8082
#  ssl:
#  enabled: true
#  key-store: classpath:keystore.p12
#  key-store-password: password
#  key-store-type: PKCS12
#  key-alias: reactive
spring:
#  webflux:
#    base-path: /
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      client:
        registration:
          google:
            client-id: 885176901627-7ar6btfh7kvnp6v2vah8hmh56l5mnn3n.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: https://localhost:8082/login/oauth2/code/google
            access-type: offline
            prompt: consent
        provider:
          google:
            issuer-uri: https://accounts.google.com
  application:
    name: service2reactive
  datasource:
    url: jdbc:h2:mem:testdb # In-memory H2 database URL
    driverClassName: org.h2.Driver # H2 database driver
    username: sa # Default username for H2
    password: # No password by default
    r2dbc:
      url: r2dbc:h2:mem:///testdb # Reactive H2 database URL
      username: sa # Default username for H2
      password: # No password by default
    h2:
      console:
        enabled: true # Enable H2 console for development
        path: /h2-console # Path to access the H2 console
#    sql:
#      init:
#        mode: always # Always initialize the database schema

web-client-endpoints:
  epm-api:
    url: https://epm.ecotep.com.ua
logging:
  level:
    org.springframework.security: DEBUG


