
spring:
  application:
    name: service2reactive
  datasource:
    url: jdbc:h2:mem:testdb # In-memory H2 database URL
    driverClassName: org.h2.Driver # H2 database driver
    username: sa # Default username for H2
    password: # No password by default
    r2dbc:
      url: r2dbc:h2:mem:///testdb # Reactive H2 database URL
      username: sa # Default username for H2
      password: # No password by default
    h2:
      console:
        enabled: true # Enable H2 console for development
        path: /h2-console # Path to access the H2 console
#    sql:
#      init:
#        mode: always # Always initialize the database schema
    jpa:
      hibernate:
        ddl-auto: none # Disable automatic schema generation by Hibernate
      show-sql: true
